account/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views
from . import views


app_name = "account"

urlpatterns = [
    path('account/', views.dashboard, name='dashboard'),
    path('account/view/edit/profile/',
         views.view_edit_profile, name='view_edit_profile'),
    path('accounts/change_password/',
         views.change_password, name='change_password'),
]

administrator/urls.py
from django.urls import path
from . import views
# Create your forms here


app_name = 'administrator'

urlpatterns = [
    path('dmca/create/user/', views.create_user, name='create_user'),
    path('dmca/create/user/done/', views.create_user_done, name='create_user_done'),
    path('dmca/view/users/', views.view_users, name='view_users'),
    path('dmca/delete/user/<int:user_id>/',
         views.delete_user, name='delete_user'),
    path('dmca/edit/user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('dmca/edit/level/section/<int:level_section_id>',
         views.edit_level_section, name='edit_level_section'),
    path('dmca/view/level/section/',
         views.view_level_section, name='view_level_section'),
    path('dmca/delete/level/section/<int:level_section_id>',
         views.delete_level_section, name='delete_level_section'),
    path('dmca/create/subject/<int:user_id>/',
         views.create_subject, name='create_subject'),
    path('dmca/edit/subject/<slug:subject_slug>/<int:user_id>/',
         views.edit_subject, name='edit_subject'),
    path('dmca/delete/subject/<slug:subject_slug>/<int:user_id>/',
         views.delete_subject, name='delete_subject'),
    path('dmca/enroll/subject/<int:user_id>/<user_full_name>/',
         views.enrollment_admission_student, name='enrollment_admission'),
    path('dmca/delete/subject/grade/<int:user_id>/<user_full_name>/<int:subject_grade_id>/',
         views.delete_subject_grade, name='delete_subject_grade'),
    path('dmca/edit/subject/grade/<int:user_id>/<user_full_name>/<int:subject_grade_id>/',
         views.edit_subjectGrade_admin, name='edit_subjectGrade_admin'),
    path('dmca/create/final/grade/',
         views.create_student_finalLevelGradeAdmin, name='create_student_finalLevelGradeAdmin'),
    path('dmca/edit/final/grade/<int:final_grade_id>/<user_full_name>/',
         views.edit_student_finalLevelGradeAdmin, name='edit_student_finalLevelGradeAdmin'),
    path('dmca/delete/grade/<int:final_grade_id>/<user_full_name>/',
         views.delete_student_finalLevelGradeAdmin, name='delete_student_finalLevelGradeAdmin'),
    path('dmca/update/statement/<int:statement_id>/<student_full_name>/<int:student_id>/',
         views.update_statement_admin, name='update_statement_admin'),
    path('dmca/view/statement/<user_full_name>/<int:user_id>/',
         views.view_statement_admin, name='view_statement_admin'),
    path('dmca/delete/statement/<int:statement_id>/<student_full_name>/<int:student_id>/',
         views.delete_statement_admin, name='delete_statement_admin'),
    path('dmca/view/create/year-level/',
         views.view_create_year_level, name='view_create_year_level'),
    path('dmca/view/appointment-requests/',
         views.view_appointment_request, name='view_appointment_request'),
    path('dmca/delete/view/appointment-request/<int:appointment_request_id>/',
         views.delete_appointment_request, name='delete_appointment_request'),
    path('dmca/update/appointment-request/<int:appointment_request_id>/<slug:appointment_request_slug>/',
         views.update_appointment_request, name='update_appointment_request'),
]

projectDMCA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'DMCA Administration'
admin.site.index_title = 'DMCA Administration'
admin.site.site_title = 'Admin Site'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='account')),
    # login, logout and password_reset form
    path('account/', include('django.contrib.auth.urls')),
    path('administrator/', include('administrator.urls', namespace='administrator')),
    path('announcement/', include('announcement.urls', namespace='announcement')),
    path('academic/', include('grading_system.urls', namespace='grading_system')),
    path('accounting/transaction/', include('accounting_transaction.urls',
                                            namespace='accounting_transaction')),
    path('', include('admission.urls', namespace='admission')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

administrator/models.py
from django.db import models
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here

admission/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify
# Create your models here.

phone_regex = RegexValidator(
    regex=r'^\d{4}\-\d{3}\-\d{4}$', message="Accepted Format:0999-999-9999.")
age_regex = RegexValidator(
    regex=r'^\d{2}\-yrs old$', message="Accepted Format: 'age'-yrs old")

GENDER_CHOICES = (('male', 'Male'), ('female', 'Female'))


class AppointmentRequest(models.Model):
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=255, unique=True)
    age = models.CharField(max_length=10)
    birthday = models.DateField(blank=True, null=True)
    gender = models.CharField(
        max_length=25, choices=GENDER_CHOICES,
        default='male'
    )
    address = models.CharField(max_length=255, blank=True, null=True)
    guardian = models.CharField(max_length=50, blank=True, null=True)
    relationship = models.CharField(max_length=50, blank=True, null=True)
    contact_number = models.CharField(
        validators=[phone_regex, ],
        max_length=15,
        blank=True, null=True,
        help_text="Please use the format: 0999-999-9999"
    )
    is_active = models.BooleanField(
        default=True, verbose_name='Active Request?')
    schedule = models.DateField(blank=True, null=True)
    time = models.TimeField(blank=True, null=True)
    slug = models.SlugField(max_length=50, blank=True,
                            null=True, editable=False)
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name_plural = "Appointment Requests"
        unique_together = ('is_active', 'email')
        ordering = ('-date_created', )

    def __str__(self):
        return self.first_name + " " + self.last_name

    @property
    def get_complete_name(self):
        if self.middle_name:
            return self.first_name + " " + self.middle_name + " " + self.last_name
        return self.first_name + " " + self.last_name


@receiver(post_save, sender=AppointmentRequest)
def generate_appointment_slug(sender, **kwargs):
    if kwargs['created'] or kwargs['instance'].slug is None:
        kwargs['instance'].slug = slugify(str(kwargs['instance'].date_created) + " " +
                                          str(kwargs['instance'].id))
        kwargs['instance'].save()

account/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.forms import Textarea, FileInput
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from .models import (
    Profile, LevelAndSection, Level,
    StudentProfile, StaffProfile, FacultyProfile
)

User = get_user_model()


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation',
        widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = (
            'email', 'first_name',
            'last_name', 'middle_name',
            'date_of_birth', 'gender', 'address',
            'is_active', 'is_student',
            'is_teacher', 'is_staff', 'is_superuser'
        )
        labels = {
            'is_active': 'Active',
            'is_student': 'Student',
            'is_teacher': 'Teacher',
            'is_staff': 'Staff',
            'is_superuser': 'Superuser'
        }

    date_of_birth = forms.DateField(
        widget=forms.DateInput(format='%m/%d/%Y',
                               attrs={'class': 'datepicker', 'placeholder': 'mm/dd/yyyy'}),
        input_formats=('%m/%d/%Y',)
    )

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = (
            'email', 'first_name',
            'last_name', 'middle_name',
            'date_of_birth', 'gender', 'address',
            'is_active', 'is_student',
            'is_teacher', 'is_staff',
            'is_superuser', 'password'
        )

        labels = {
            'is_active': 'Active',
            'is_student': 'Student',
            'is_teacher': 'Teacher',
            'is_staff': 'Staff',
            'is_superuser': 'Superuser'
        }

    date_of_birth = forms.DateField(
        widget=forms.DateInput(format='%m/%d/%Y',
                               attrs={'class': 'datepicker', 'placeholder': 'mm/dd/yyyy'}),
        input_formats=('%m/%d/%Y',)
    )
    is_active = forms.BooleanField(
        widget=forms.CheckboxInput(
            attrs={'class': 'checkbox'}
        )
    )

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class UserEditForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = (
            'email', 'first_name',
            'last_name', 'middle_name',
            'date_of_birth', 'gender', 'address',
            'is_active', 'password'
        )

        labels = {
            'is_active': 'Active',
            'is_student': 'Student',
            'is_teacher': 'Teacher',
            'is_staff': 'Staff',
            'is_superuser': 'Superuser'
        }

    date_of_birth = forms.DateField(
        widget=forms.DateInput(
            format='%m/%d/%Y',
            attrs={'class': 'datepicker', 'placeholder': 'mm/dd/yyyy'}
        ),
        input_formats=('%m/%d/%Y',)
    )

    def clean_password(self):
        return self.initial["password"]


class UserAdmin(BaseUserAdmin):
    # The forms to add and change user instances
    form = UserChangeForm  # update view
    add_form = UserCreationForm  # create view

    # The fields to be used in displaying the User model.
    # These override the definitions on the base UserAdmin
    # that reference specific fields on auth.User.
    list_display = (
        'email', 'is_active',
        'is_student', 'is_teacher',
        'is_staff', 'is_superuser'
    )
    list_filter = ('is_student', 'is_teacher', 'is_staff', 'is_superuser',)
    fieldsets = (
        (None, {'fields': ('email', 'password')}),
        ('Personal info', {'fields': (
            'first_name', 'last_name', 'middle_name', 'date_of_birth', 'gender', 'address')}),
        ('Status', {'fields': ('is_active',), }),
        ('Permissions', {'fields': ('is_student',
                                    'is_teacher', 'is_staff', 'is_superuser')}),
    )

    # add_fieldsets is not a standard ModelAdmin attribute. UserAdmin
    # overrides get_fieldsets to use this attribute when creating a user.
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': (
                'email', 'first_name',
                'last_name', 'middle_name',
                'date_of_birth', 'gender', 'address',
                'is_active', 'is_student',
                'is_teacher', 'is_staff',
                'is_superuser', 'password1',
                'password2'
            )
        }
         ),
    )
    search_fields = ('email',)
    ordering = ('email',)
    filter_horizontal = ()


# for administrator/staff only
class ProfileCreateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo', 'phone_number', 'age']

        labels = {'photo': 'Profile Picture', 'age': 'Age'}

        widgets = {
            'phone_number': Textarea(attrs={'placeholder': '0999-999-9999', 'cols': 20, 'rows': 1})
        }


# for students/teachers/staff personal use only
class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo', 'phone_number', 'age']

        labels = {
            'photo': 'Profile Picture',
        }

        widgets = {
            'photo': FileInput(attrs={'class': 'file-field'})
        }


# for ordinary users only
class PersonalForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['date_of_birth', 'address']

        labels = {
            'date_of_birth': 'Birthday',
        }

    date_of_birth = forms.DateField(
        widget=forms.DateInput(
            attrs={'class': 'datepicker', 'placeholder': 'mm/dd/yyyy'},
            format='%m/%d/%Y'
        ),
        input_formats=('%m/%d/%Y',)
    )

    address = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': '', 'rows': 5, 'cols': 100}
        )
    )


# student profile form for admin
class StudentProfileAdminForm(forms.ModelForm):
    class Meta:
        model = StudentProfile
        exclude = ['user', ]
        labels = {
            'guardian_contact_number': 'Guardian\'s Contact Number',
        }


# faculty profile form for admin
class FacultyProfileAdminForm(forms.ModelForm):
    class Meta:
        model = FacultyProfile
        exclude = ['user', ]
        labels = {'designated_year_level': 'Designated Year Level'}


# staff profile form for admin
class StaffProfileAdminForm(forms.ModelForm):
    class Meta:
        model = StaffProfile
        exclude = ['user', ]


# student personal profile form
class StudentPersonalProfileForm(forms.ModelForm):
    class Meta:
        model = StudentProfile
        exclude = ['level_and_section', 'user', 'learner_reference_number']
        labels = {
            'guardian_contact_number': 'Guardian\'s Contact Number',
        }


# faculty personal profile form
class FacultyPersonalProfileForm(forms.ModelForm):
    class Meta:
        model = FacultyProfile
        exclude = ['user', 'designated_year_level']
        labels = {
            'school_graduated': 'School Graduated',
            'major': 'Course Major'
        }


# staff personal profile form
class StaffPersonalProfileForm(forms.ModelForm):
    class Meta:
        model = StaffProfile
        exclude = ['user', ]
        labels = {}


# for administrator/staff only
class LevelAndSectionForm(forms.ModelForm):
    class Meta:
        model = LevelAndSection
        fields = ['level', 'section', 'adviser']


class LevelForm(forms.ModelForm):
    class Meta:
        model = Level
        exclude = ['date_created', 'updated']

administrator/forms.py
from django import forms
from django.contrib.auth import get_user_model
from admission.models import AppointmentRequest

# Create forms here

User = get_user_model()


class AppointmentRequestFormAdmin(forms.ModelForm):
    class Meta:
        model = AppointmentRequest
        exclude = ['date_created', ]

admission/forms.py
from django import forms
from .models import AppointmentRequest


class AppointmentRequestForm(forms.ModelForm):
    class Meta:
        model = AppointmentRequest
        exclude = ['date_created', 'is_active']
        labels = {
            'schedule': 'Date and Time of Appointment',
        }

    birthday = forms.DateField(
        widget=forms.DateInput(
            attrs={'class': 'datepicker', }), )

    schedule = forms.DateField(
        widget=forms.DateInput(
            attrs={'class': 'datepicker', })
    )

    time = forms.TimeField(
        widget=forms.TimeInput(
            attrs={'class': 'timepicker', 'placeholder': 'hour:min'})
    )

administrator/templates/create_student_finalgrade_admin.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ request.user.get_short_name }}| {{ request.user.staff_profile.position }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    <form method="POST" action=".">
        {% csrf_token %}
        {{ finalGrade_form.as_p }}
        <input type="submit" value="Submit"/>
    </form>
    <a href="{% url 'administrator:view_users' %}" >View Users</a>
</body>
</html>

administrator/templates/create_subject.html
{% extends 'base.html' %}
    {% block title %}{{ request.user.get_short_name }} | Create Subject{% endblock title %}
    {% load staticfiles %}
    {% block content %}
    <div class="white">
        <div class="row">
        <br>

    <div class="col s12 m12 l3">
        <div class="col s12">
          <div class="card darken-1">
            <div class="card-content white-text">
                <center><img src="{% static 'img/language.svg' %}" style="object-fit: fill; height: 150px"><h5><b> Edit Section</b></h5></center>
                <span class="card-title"><h4 class="center black-text"><b>Create Subject</b></h4></span>
                <div>
                    <form method="POST" action="{% url 'administrator:create_subject' user_id %}">
                        {% csrf_token %}
                        {{ create_subject_form.as_p }}
                        <button class="btn waves-effect" style="width:100%" type="submit"><i class="material-icons left">add</i> Create Subject</button>
                    </form>
                </div>
            </div>
          </div>
        </div>
      </div>


      <div class="card col s12 m12 l9">
          <div class="card-content">
              <span class="card-title"><h4 class="center black-text"><b>Subjects</b></h4></span>
              <table class="highlight responsive-table centered" border="1">
                  <thead>
                      <tr>
                        <th>Subject</th>
                        <th>Ref. Code</th>
                        <th>Year and Section</th>
                        <th>Designated Instructor</th>
                        <th>Option</th>
                      </tr>
                  </thead>
                    
                    
                    <tbody>
                        {% for subject in subjects %}
                        <tr>
                            <td> {{ subject.subject_name }}</td>
                            <td> {{ subject.slug }}</td>
                            <td> {{ subject.level_and_section }}</td>
                            <td> {{ subject.designated_instructor }}</td>
                            <td><a class="btn-flat" href="{% url 'administrator:edit_subject' subject.slug 0 %}">
                                <i class="material-icons center">edit</i></a> 
                                <a class="btn-flat" href="{% url 'administrator:delete_subject' subject.slug 0 %}" 
                                onclick="return confirm('Are you sure you want to DELETE {{subject.subject_name}} for {{subject.level_and_section}}?')">
                                <i class="material-icons center">delete</i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                        
                </table>
                <b><h6><hr class="grey"></h6></b>
                <div class="pagination right">
                    <span class="step-links">
                        {% if subjects.has_previous %}
                        <li class="waves-effect"><a href="?page={{ subjects.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
                        <li class="waves-effect"><a href="?page=1"><i class="material-icons">first_page</i></a></li>
                        {% endif %}
                        <li>
                        <a class="current">
                            Page {{ subjects.number }} of {{ subjects.paginator.num_pages }}.
                        </a>
                        </li>
                        {% if subjects.has_next %}
                        <li class="waves-effect"><a href="?page={{ subjects.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
                        <li class="waves-effect"><a href="?page={{ subjects.paginator.num_pages }}"><i class="material-icons">last_page</i></a></li>
                        {% endif %}
                    </span>
                </div>
          </div>
            
<br>
      </div>
    
</div>
    <br>

</div>
    {% endblock content %}

administrator/templates/edit_student_finalgrade_admin.html
{% extends 'base.html' %}
{% block title %}{{ request.user.get_full_name }} | Dashboard{% endblock title %}
{% block content %}
{% load announcement_tags %}
{% load staticfiles %}
<div class="white">
    <br><br>
    <div class="container">
        <div class="card">
            <div class="card-content">
                <form method="POST" action="{% url 'administrator:edit_student_finalLevelGradeAdmin' finalGrade.id student_user.get_full_name %}">
                    {% csrf_token %}
                    <p><label for="id_school_year">School year:</label> <select name="school_year" id="id_school_year">
                            {% for option in finalGrade_form.school_year %}
                            {{ option }}
                            {% endfor %}
                        </select></p>
                    <p><label for="id_grade">Final Grade:</label> <input type="number" name="grade" step="0.0001" id="id_grade"
                            value="{{ finalGrade_form.grade.value }}"></p>
                    <p><label for="id_comment">Comment:</label> <textarea name="comment" cols="40" rows="10" id="id_comment">{{ finalGrade_form.comment.value }}
          </textarea></p>
                    {% if finalGrade_form.is_finalized.value %}
                    <p>
                        <label for="id_is_finalized">
                            <input type="checkbox" name="is_finalized" id="id_is_finalized" checked>
                            <span>Finalized?</span>
                        </label>
                        <span class="helptext">Once finalized, you can no longer make any more changes.</span>
                    </p>
                    {% else %}
                    <p><label for="id_is_finalized">
                            <input type="checkbox" name="is_finalized" id="id_is_finalized">
                            <span>Finalized?</span>
                        </label>
                        <span class="helptext">Once finalized, you can no longer make any more changes.</span>
                    </p>
                    {% endif %}
                    <input type="submit" value="Submit" />
                </form>
            </div>
        </div>
        {% for message in messages %}
        <p>
            {{ message }}
        </p>
        {% endfor %}

        <a href="{% url 'administrator:enrollment_admission' student_user.id student_user.get_full_name %}">Back</a>
    </div>
</div>
{% endblock content %}

administrator/templates/update_appointment_request.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
Manage Request
{% endblock title%}
{% block content %}
<div class="white">
<br>
<div class="container">
    <div class="card">
        <div class="card-content">
            <center><img src="{% static 'img/curriculum.svg' %}" style="object-fit: fill; max-height: 180px"></center>
            <div id="modal1" class="modal">
                <div class="modal-content">
                    {% for message in messages %}
                    <center>
                        <img src="{% static 'img/checked.svg' %}" style="object-fit: fill; max-height: 100px"> 
                        <br><h5><b>{{ message }}</b></h5>
                    </center>
                    {% endfor %} 
                </div>
                <div class="modal-footer">
                    <a href="{% url 'administrator:view_appointment_request' %}" class="modal-close waves-effect waves-green btn-flat">OK</a>
                </div>
            </div>
            <form method="POST" action="{% url 'administrator:update_appointment_request' appointment_request_instance.id appointment_request_instance.slug %}">
                <button id="submit_btn" class="waves-effect waves-light btn modal-trigger hiddendiv" href="#modal1">Modal</button>
                {% csrf_token %}
                <!-- {{ update_appointment_request_form.as_p }} -->
                <p>
                    <label for="id_first_name">First name:</label> 
                    <input type="text" name="first_name" value="{{ update_appointment_request_form.first_name.value }}" maxlength="50" required id="id_first_name"></p>
                <p>
                    <label for="id_middle_name">Middle name:</label>
                    <input type="text" name="middle_name" value="{{ update_appointment_request_form.middle_name.value }}" maxlength="50" id="id_middle_name">
                </p>
                <p>
                    <label for="id_last_name">Last name:</label>
                    <input type="text" name="last_name" value="{{ update_appointment_request_form.last_name.value }}" maxlength="50" required id="id_last_name">
                </p>
                <p>
                    <label for="id_email">Email:</label> 
                    <input type="email" name="email" value="{{ update_appointment_request_form.email.value }}" maxlength="255" required id="id_email">
                </p>
                <p>
                    <label for="id_age">Age:</label> 
                    <input type="text" name="age" value="{{ update_appointment_request_form.age.value }}" maxlength="10" required id="id_age">
                </p>
                <p>
                    <label for="id_birthday">Birthday:</label> 
                    <input type="text" name="birthday" value="{{ update_appointment_request_form.birthday.value|date:'SHORT_DATE_FORMAT' }}" id="id_birthday">
                </p>
                <p>
                    <label for="id_gender">Gender:</label> 
                    <select name="gender" id="id_gender">
                        {% if update_appointment_request_form.gender.value == "male" %}
                        <option value="male" selected>Male</option>
                        <option value="female">Female</option>
                        {% else %}
                        <option value="male">Male</option>
                        <option value="female" selected>Female</option>
                        {% endif %}
                    </select>
                </p>
                <p>
                    <label for="id_address">Address:</label> 
                    <input type="text" name="address" value="{{ update_appointment_request_form.address.value }}" maxlength="255" id="id_address">
                </p>
                <p>
                    <label for="id_guardian">Guardian:</label>
                    <input type="text" name="guardian" value="{{ update_appointment_request_form.guardian.value }}" maxlength="50" id="id_guardian">
                </p>
                <p>
                    <label for="id_relationship">Relationship:</label> 
                    <input type="text" name="relationship" value="{{ update_appointment_request_form.relationship.value }}" maxlength="50" id="id_relationship">
                </p>
                <p>
                    <label for="id_contact_number">Contact number:</label> 
                    <input type="text" name="contact_number" value="{{ update_appointment_request_form.contact_number.value }}" maxlength="15" id="id_contact_number"> 
                    <span class="helptext">Please use the format: 0999-999-9999</span>
                </p>
                <p>
                    <label for="id_is_active">
                            {% if update_appointment_request_form.is_active.value %}
                            <input type="checkbox" name="is_active" id="id_is_active" checked>
                            {% else %}
                            <input type="checkbox" name="is_active" id="id_is_active">
                            {% endif %}
                            <span>Active Request?</span>
                    </label>
                </p>
                <p>
                    <label for="id_schedule">Schedule</label> <input class="datepicker" type="text" name="schedule" value="{{ update_appointment_request_form.schedule.value|date:'SHORT_DATE_FORMAT' }}" id="id_schedule">
                </p>
                <p>
                    <label for="id_time">Time</label> <input class="timepicker" type="text" name="time" value="{{ update_appointment_request_form.time.value|title }}" id="id_time">
                </p>
                <input class="btn" type="submit" value="Update" style="width:100%"/>
            </form>
        </div>
    </div>
</div>
<br>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('.datepicker');
        var instances = M.Datepicker.init(elems, {
          format: 'm/d/yyyy',
          yearRange: [1980, 2018]
        });
      });
      document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems, {});
      });
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.timepicker');
        var instances = M.Timepicker.init(elems, {
            twelveHour: false
        });
      })
</script>
</div>
{% endblock content %}