account/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views
from . import views


app_name = "account"

urlpatterns = [
    path('account/', views.dashboard, name='dashboard'),
    path('account/view/edit/profile/',
         views.view_edit_profile, name='view_edit_profile'),
    path('accounts/change_password/',
         views.change_password, name='change_password'),
]

grading_system/urls.py
from django.urls import path
from . import views

app_name = 'grading_system'

urlpatterns = [
    path('faculty/assigned/subjects/',
         views.view_assigned_subject, name="view_assigned_subject"),
    path('faculty/view/students/per/subject/<int:level_section_id>/<int:subject_id>/',
         views.view_students_per_subject, name="view_students_per_subject"),
    path('faculty/view/student/profile/<int:user_id>/<short_name>/',
         views.view_student_profile, name='view_student_profile'),
    path('faculty/edit/student/subject-grade/<int:user_id>/<user_full_name>/<int:subject_grade_id>/',
         views.edit_student_subjectgrade, name='edit_student_subjectGrade'),
    path('faculty/view/student/final-grade/',
         views.view_students_finalgrade, name='view_students_finalgrade'),
    path('faculty/edit/student/final-grade/<int:user_id>/<int:level_id>/',
         views.edit_student_finalgrade, name='edit_student_finalgrade'),
    path('student/subject/<student_level>/<student_section>/',
         views.student_level_section_subject, name="student_level_section_subject"),
    path('student/view/faculty/profile/<int:user_id>/<short_name>/',
         views.view_faculty_profile, name='view_faculty_profile'),
    path('student/view/all/grades/',
         views.view_all_grades, name='view_all_grades'),
]

projectDMCA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'DMCA Administration'
admin.site.index_title = 'DMCA Administration'
admin.site.site_title = 'Admin Site'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='account')),
    # login, logout and password_reset form
    path('account/', include('django.contrib.auth.urls')),
    path('administrator/', include('administrator.urls', namespace='administrator')),
    path('announcement/', include('announcement.urls', namespace='announcement')),
    path('academic/', include('grading_system.urls', namespace='grading_system')),
    path('accounting/transaction/', include('accounting_transaction.urls',
                                            namespace='accounting_transaction')),
    path('', include('admission.urls', namespace='admission')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

grading_system/models.py
from django.db import models
from django.contrib.auth import get_user_model
from account.models import LevelAndSection, Level
from datetime import datetime
from django.utils.text import slugify
from account.models import FacultyProfile, StudentProfile
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

SY = []
for year in range(2010, datetime.now().year + 15):
    SY.append((str(year) + "-" + str(year + 1), str(year) + "-" + str(year + 1)))

User = get_user_model()


class Subject(models.Model):
    subject_name = models.CharField(max_length=50)
    level_and_section = models.ForeignKey(
        LevelAndSection, on_delete=models.SET_NULL, null=True, blank=True)
    designated_instructor = models.ForeignKey(
        FacultyProfile, related_name="assigned_subject", on_delete=models.SET_NULL, null=True, blank=True)
    schedule = models.CharField(max_length=255, null=True, blank=True)
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    slug = models.SlugField(
        max_length=250, null=True, blank=True, editable=False)
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        ordering = ['-date_created', ]
        unique_together = ('subject_name', 'level_and_section')

    def __str__(self):
        if self.level_and_section:
            return "{}, {}-{}".format(
                self.subject_name,
                self.level_and_section.level,
                self.level_and_section.section
            )
        return self.subject_name


class SubjectGrade(models.Model):
    student = models.ForeignKey(
        StudentProfile, on_delete=models.CASCADE, related_name='grade')
    school_year = models.CharField(
        max_length=25, choices=SY, default=str(datetime.now().year) + "-" + str(datetime.now().year + 1))
    subject = models.ForeignKey(
        Subject, on_delete=models.DO_NOTHING, null=True, blank=True, related_name='subject_grade')
    instructor = models.ForeignKey(
        FacultyProfile, null=True, blank=True, on_delete=models.SET_NULL, related_name='given_grade')
    first_quarter = models.DecimalField(
        max_digits=10, decimal_places=4, null=True, blank=True)
    second_quarter = models.DecimalField(
        max_digits=10, decimal_places=4, null=True, blank=True)
    third_quarter = models.DecimalField(
        max_digits=10, decimal_places=4, null=True, blank=True)
    fourth_quarter = models.DecimalField(
        max_digits=10, decimal_places=4, null=True, blank=True)
    final_subject_grade = models.DecimalField(
        max_digits=10, decimal_places=4, null=True, blank=True)
    is_finalized = models.BooleanField(
        verbose_name="Finalized?", default=False,
        help_text="Once finalized, you can no longer make any more changes.")
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        unique_together = ('student', 'subject')

    def __str__(self):
        return "Subject: {} Student: {}".format(
            self.subject.subject_name,
            self.student.user.get_full_name
        )

    def save(self, *args, **kwargs):

        if self.first_quarter and self.second_quarter and self.third_quarter and self.fourth_quarter:
            self.final_subject_grade = (
                                               self.first_quarter + self.second_quarter +
                                               self.third_quarter + self.fourth_quarter
                                       ) / 4
        else:
            self.final_subject_grade = 0
        super(SubjectGrade, self).save(*args, **kwargs)


class FinalGrade(models.Model):
    student = models.ForeignKey(
        StudentProfile, on_delete=models.CASCADE, related_name='finalGrade')
    level = models.ForeignKey(
        Level, on_delete=models.SET_NULL, related_name='final', null=True, blank=True)
    school_year = models.CharField(
        max_length=25, choices=SY,
        default=str(datetime.now().year) + "-" + str(datetime.now().year + 1))
    grade = models.DecimalField(
        max_digits=10, decimal_places=4, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    is_finalized = models.BooleanField(
        verbose_name="Finalized?", default=False,
        help_text="Once finalized, you can no longer make any more changes."
    )
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        unique_together = ('student', 'level')

    def __str__(self):
        return "{} GWA:{} SY: {}".format(self.student.user.get_full_name, self.grade, self.school_year)


@receiver(post_save, sender=Subject)
def create_dynamic_subject_slug(sender, **kwargs):
    if kwargs['created']:
        kwargs['instance'].slug = slugify(
            kwargs['instance'].subject_name + " " + str(kwargs['instance'].id))
        kwargs['instance'].save()


@receiver(post_save, sender=FinalGrade)
def sync_subject_school_year(sender, **kwargs):
    subjects = SubjectGrade.objects.filter(
        subject__level_and_section__level=kwargs['instance'].level)
    sample = subjects.first()
    if sample.school_year != kwargs['instance'].school_year:
        for subject in subjects:
            subject.school_year = kwargs['instance'].school_year
            subject.save()

grading_system/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import (FinalGrade, Subject, SubjectGrade)


User = get_user_model()


# for administrator use only
class SubjectCreateForm(forms.ModelForm):
    class Meta:
        model = Subject
        exclude = ['date_created', 'updated', 'slug']


# for administrator use only
class SubjectGradeCreateForm(forms.ModelForm):
    class Meta:
        model = SubjectGrade
        exclude = [
            'date_created', 'updated',
            'student', 'instructor', 'subject'
        ]
        labels = {
            'is_finalized': 'Finalized?',
        }


# for faculty use only
class SubjectGradeEditForm(forms.ModelForm):
    class Meta:
        model = SubjectGrade
        exclude = [
            'date_created', 'updated',
            'student', 'school_year',
            'subject', 'instructor']
        labels = {
            'is_finalized': 'Finalized?',
        }


# for administrator use only
class FinalGradeCreateForm(forms.ModelForm):
    class Meta:
        model = FinalGrade
        exclude = ['student', 'date_created', 'updated', 'level']
        labels = {
            'is_finalized': 'Finalized?',
            'grade': 'Final Grade'
        }


# for faculty use only
class FinalGradeEditForm(forms.ModelForm):
    class Meta:
        model = FinalGrade
        exclude = [
            'date_created', 'updated',
            'student', 'level',
            'school_year'
        ]
        labels = {
            'is_finalized': 'Finalized?',
            'grade': 'Final Grade'
        }

grading_system/templates/faculty/edit_student_finalLevelGrade.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Final Grade|{{student_user.get_full_name}}|{{ student_user.student_profile.level_and_section }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    
</body>
</html>

grading_system/templates/faculty/edit_student_finalgrade.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}SY: {{ final_LevelGrade.school_year }} | Final Grade |{{student_user.get_full_name}}|{{ student_user.student_profile.level_and_section }}{% endblock title %}
{% block content %}
<div class="white">
<br><br>
<div>
    <div>
        <p>Student: {{ student_user.get_full_name }}</p>
        <p>Section: {{ student_user.student_profile.level_and_section }}</p>
    </div>

    <h3>Subjects</h3>
    <div>
        <table border="1">
            <th>Subject</th>
            <th>SY</th>
            <th>First Quarter</th>
            <th>Second Quarter</th>
            <th>Third Quarter</th>
            <th>Fourth Quarter</th>
            <th>Final Subject Grade</th>
            <th>Option</th>
            {% for each_subject in year_level_subjects %}
                <tr>
                    <td>{{ each_subject.subject.subject_name }}</td>
                    <td>{{ each_subject.school_year }}</td>
                    {% if each_subject.first_quarter %}
                        <td>{{ each_subject.first_quarter }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}

                    {% if each_subject.second_quarter %}
                        <td>{{ each_subject.second_quarter }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}

                    {% if each_subject.third_quarter %}
                        <td>{{ each_subject.third_quarter }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}

                    {% if each_subject.fourth_quarter %}
                        <td>{{ each_subject.fourth_quarter }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}

                    {% if each_subject.final_subject_grade %}
                        <td>{{ each_subject.final_subject_grade }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}

                    <td>
                        <a href="{% url 'grading_system:edit_student_subjectGrade' student_user.id student_user.get_full_name each_subject.id %}" target="_blank">
                            Update
                        </a>
                    </td>
                </tr>
        {% endfor %}
        </table>
    </div>
    <ul>  
    {% for message in messages %}
        <li>{{message}}</li>
    {% endfor %}
    </ul>
    <form method="POST" action="{% url 'grading_system:edit_student_finalgrade' student_user.id level_and_section.level.id %}">
        {% csrf_token %}
        <p><label for="id_grade">Final Grade:</label> <input type="number" name="grade" step="0.0001" id="id_grade"
            value="{{ finalGrade_form.grade.value }}"></p>
    <p><label for="id_comment">Comment:</label> <textarea name="comment" cols="40" rows="10" id="id_comment">{{ finalGrade_form.comment.value }}
</textarea></p>
    {% if finalGrade_form.is_finalized.value %}
    <p>
        <label for="id_is_finalized">
            <input type="checkbox" name="is_finalized" id="id_is_finalized" checked>
            <span>Finalized?</span>
        </label>
        <span class="helptext">Once finalized, you can no longer make any more changes.</span>
    </p>
    {% else %}
    <p><label for="id_is_finalized">
            <input type="checkbox" name="is_finalized" id="id_is_finalized">
            <span>Finalized?</span>
        </label>
        <span class="helptext">Once finalized, you can no longer make any more changes.</span>
    </p>
    {% endif %}
        <input type="submit" value="Submit" />
    </form>
    <a href="{% url 'grading_system:view_assigned_subject' %}" >Subjects</a>
    <a href="{% url 'grading_system:view_students_finalgrade' %}" >Back</a>
</div>

</div>
{% endblock content %}

grading_system/templates/faculty/edit_student_subjectGrade.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ subjectGrade.subject.subject_name }}|{{student_user.get_short_name}}|{{
student_user.student_profile.level_and_section }}{% endblock title %}
{% block content %}
<div class="white">
    <br><br>
    <div class="container">
        <a href="{% url 'grading_system:view_students_per_subject' level_and_section.id subjectGrade.subject.id  %}">Students
            Enrolled in {{ subjectGrade.subject.subject_name }} {{ student_user.student_profile.level_and_section }}</a>
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        <ul style="list-style-type:none;">
            <li>Student: {{ student_user.get_full_name }}</li>
            <li>Subject: {{ subjectGrade.subject.subject_name }}</li>
            <li>Year and Section: {{ student_user.student_profile.level_and_section }}</li>
        </ul>

        <form method="POST" action="{% url 'grading_system:edit_student_subjectGrade' student_user.id student_user.get_full_name subjectGrade.id %}">
            {% csrf_token %}
            <p><label for="id_first_quarter">First quarter:</label> <input type="number" name="first_quarter" step="0.0001"
                    id="id_first_quarter" value="{{ subjectGrade_edit_form.first_quarter.value }}"></p>
            <p><label for="id_second_quarter">Second quarter:</label> <input type="number" name="second_quarter" step="0.0001"
                    id="id_second_quarter" value="{{ subjectGrade_edit_form.second_quarter.value }}"></p>
            <p><label for="id_third_quarter">Third quarter:</label> <input type="number" name="third_quarter" step="0.0001"
                    id="id_third_quarter" value="{{ subjectGrade_edit_form.third_quarter.value }}"></p>
            <p><label for="id_fourth_quarter">Fourth quarter:</label> <input type="number" name="fourth_quarter" step="0.0001"
                    id="id_fourth_quarter" value="{{ subjectGrade_edit_form.fourth_quarter.value }}"></p>
            <p><label for="id_final_subject_grade">Final subject grade:</label> <input type="number" name="final_subject_grade"
                    step="0.0001" id="id_final_subject_grade" value="{{ subjectGrade_edit_form.final_subject_grade.value }}"></p>

            <p><label for="id_is_finalized">
                    {% if subjectGrade_edit_form.is_finalized.value %}
                    <input type="checkbox" name="is_finalized" id="id_is_finalized" checked>
                    {% else %}
                    <input type="checkbox" name="is_finalized" id="id_is_finalized">
                    {% endif %}
                    <span>Finalized?</span>
                </label>

                <span class="helptext">Once finalized, you can no longer make any more changes.</span>
            </p>
            <input type="submit" value="Submit" />
        </form>
        <a href="{% url 'grading_system:view_assigned_subject' %}" class="col s12">Subjects</a>
    </div>
    <br><br>
</div>
{% endblock content %}

grading_system/templates/faculty/view_assigned_subject.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} {{ current_school_year }} | Subjects | {{ request.user.get_short_name }} {% endblock title %}
{% block content %}
    <div class="white">
        <br><br>
        <div class="container">
            <div class="row">
                <div class="col l3">
                    <br><br><br>
                    <center><img src="{% static 'img/grammar.svg' %}" style="object-fit: fill; max-height: 100px"></center>
                    <h5 class="center"><b>Teacher {{ request.user.get_full_name }} </b></h5>
                    <br>
                    <br><b><h6><hr class="grey"></h6></b>
                    <br>
                    <div>
                        <a href="{% url 'grading_system:view_students_finalgrade' %}" >Final Grade</a>
                    </div>
                </div>
                <div class="col l9">
                    <div class="card hoverable">
                        <div class="card-content">
                            <h5 class="center"><b>Your Schedule </b></h5>
                            <table class="responsive-table highlight centered">
                                <thead>
                                    <tr>
                                        <th>Subject</th>
                                        <th>Year and Section</th>
                                        <th>Schedule</th>
                                        <th>Start Time</th>
                                        <th>End Time</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for subject in assigned_subjects %}
                                    <tr>
                                        <td><a  href="{% url 'grading_system:view_students_per_subject' subject.level_and_section.id subject.id %}" title="View Students Enrolled to this Subject" >{{ subject.subject_name }}</a></td>
                                        <td>{{ subject.level_and_section }}</td>
                                        <td>{{ subject.schedule }}</td>
                                        <td>{{ subject.start_time }}</td>
                                        <td>{{ subject.end_time }}</td>
                                    </tr>
                                    {% empty %}
                                    <center><img src="{% static 'img/finish-line.svg' %}" style="object-fit: fill; height: 150px"> <br><h6>Oooops!<br>It seems you haven&#39;t been assigned any subjects..</h6></center>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                </div>
                   
                    
            </div>
              
        </div>
        <br><br>
    </div>
{% endblock content %}

grading_system/templates/faculty/view_students_finalGrade.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Final Grade | {{ current_school_year }}{% endblock title %}
{% block content %}
<div class="white">
<br><br>
<div class="container">
    <div>
        <form action="" method="GET">
            <input type="text" placeholder="Search Students" name="student_query" value="{{ request.GET.student_query }}"/>
            <input type="submit" value="Search"/>
        </form>

        <table class="highlight" border="1">
                <th>Full Name</th>
                <th>LRN</th>
                <th>Email</th>
                <th>Contact Number</th>
                <th>Parent/Guardian</th>
                <th>Contact Number</th>
                <th>Year and Section</th>
                <th>Option</th>

                {% for student in students %}
                <tr>
                    <td>{{ student.get_full_name }}</td>
                    <td>{{ student.student_profile.learner_reference_number }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.profile.phone_number }}</td>
                    <td>{{ student.student_profile.guardian }}</td>
                    <td>{{ student.student_profile.guardian_contact_number }}</td>
                    <td>{{ student.student_profile.level_and_section }}</td>
                    <td><a href="{% url 'grading_system:edit_student_finalgrade' student.id student.student_profile.level_and_section.level.id  %}">Update</a></td>
                </tr>
                {% empty %}
                    Empty Result.
                {% endfor %}
            </table>    

        <div class="pagination">
            <span class="step-links">
                {% if students.has_previous %}
                    <a href="?student_page=1&student_query={{ request.GET.student_query }}">&laquo; first</a>
                    <a href="?student_page={{ student.previous_page_number }}&student_query={{ request.GET.student_query }}">previous</a>
                {% endif %}
                        
                {% if students %}
                    <span class="current">
                        Page {{ students.number }} of {{ students.paginator.num_pages }}.
                    </span>
                {% endif %}
            
                {% if students.has_next %}
                    <a href="?student_page={{ students.next_page_number }}&student_query={{ request.GET.student_query }}">next</a>
                    <a href="?student_page={{ students.paginator.num_pages }}&student_query={{ request.GET.student_query }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
        <a href="{% url 'grading_system:view_assigned_subject' %}">Subjects</a>
    </div>
</div>
<br><br>
</div>
{% endblock content %}

grading_system/templates/faculty/view_students_per_subject.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ subject.subject_name }} | {{ year_section }} | {{ current_school_year }}{% endblock title %}
{% block content %}
    <div class="white">
        <br><br>
        <div class="container">
            <div class="row">
                <div class="col l6">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div>
                                <h5 class="center">Students of<b> {{ year_section }}</b> </h5>
                                <form action="" method="GET">
                                    <div class="row">
                                        <div class="col l9">
                                            <input type="text" placeholder="Search Students" name="yearSection_query" value="{{ request.GET.yearSection_query }}"/>
                                        </div>
                                        <div class="col l3">
                                            <input class="btn btn-large" type="submit" value="Search"/>
                                        </div>
                                    </div>
                                </form>
                                {% if yearSectionStudents %}
                                <ul class="collection">
                                    {% for student in yearSectionStudents %}
                                    <li class="collection-item"> 
                                        
                                        <a  href="{% url 'grading_system:view_student_profile' student.user.id student.user.get_short_name %}">
                                            <h6>{{ student.user.get_full_name }} </h6>
                                        </a>
                                    </li>    
                                    {% endfor %}
                                </ul>
                                    
                                {% else %}
                                    No Results...
                                {% endif %}
                            </div>
                                
                            <ul class="pagination">
                                {% if yearSectionStudents.has_previous %}
                                <li class="waves-effect"><a href="?yearSection_page={{ yearSectionStudents.previous_page_number }}&yearSection_query={{ request.GET.yearSection_query }}"><i class="material-icons">chevron_left</i></a></li>
                                <li class="waves-effect"><a href="?yearSection_page=1&yearSection_query={{ request.GET.yearSection_query }}"><i class="material-icons">first_page</i></a></li>
                                {% endif %}
                                <li>
                                {% if yearSectionStudents %}
                                <a class="current">
                                    Page {{ yearSectionStudents.number }} of {{ yearSectionStudents.paginator.num_pages }}.
                                </a>
                                {% endif %}
                                </li>    
                                {% if yearSectionStudents.has_next %}
                                <li class="waves-effect"><a href="?yearSection_page={{ yearSectionStudents.next_page_number }}&yearSection_query={{ request.GET.yearSection_query }}"><i class="material-icons">chevron_right</i></a></li>
                                <li class="waves-effect"><a href="?yearSection_page={{ yearSectionStudents.paginator.num_pages }}&yearSection_query={{ request.GET.yearSection_query }}"><i class="material-icons">last_page</i></a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col l6">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div>
                                <h5 class="center">Students Enrolled in<b> {{ subject.subject_name }}</b> </h5>
                                <form action="" method="GET">
                                    <div class="row">
                                        <div class="col l9">
                                            <input type="text" placeholder="Search Students" name="enrolledStudent_query" value="{{ request.GET.enrolledStudent_query }}"/>
                                        </div>
                                        <div class="col l3">
                                            <input class="btn btn-large" type="submit" value="Search"/>
                                        </div>
                                    </div>
                                </form>
                                {% if enrolledStudentsPerSubject %}
                                <ul class="collection">
                                    {% for instance in enrolledStudentsPerSubject %}
                                        <li class="collection-item">
                                            <h6>{{ instance.student.user.get_full_name }}</h6>
                                            <a href="{% url 'grading_system:edit_student_subjectGrade' instance.student.user.id instance.student.user.get_full_name instance.id %}">
                                                Update Grade
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                                    {% else %}
                                    <center><img src="{% static 'img/fishing.svg' %}" style="object-fit: fill; width: 50%"> <br><h6>Oooops!<br>There are currently no students enrolled in this subject.</h6></center>
                                {% endif %}
                            </div> 
                            <ul class="pagination">
                                {% if enrolledStudentsPerSubject.has_previous %}
                                <li class="waves-effect"><a href="?enrolledStudent_page={{ enrolledStudentsPerSubject.previous_page_number }}&enrolledStudent_query={{ request.GET.enrolledStudent_query }}"><i class="material-icons">chevron_left</i></a></li>
                                <li class="waves-effect"><a href="?enrolledStudent_page=1&enrolledStudent_query={{ request.GET.enrolledStudent_query }}"><i class="material-icons">first_page</i></a></li>
                                {% endif %}
                                <li>  
                                {% if enrolledStudentsPerSubject %}
                                    <a class="current">
                                        Page {{ enrolledStudentsPerSubject.number }} of {{ enrolledStudentsPerSubject.paginator.num_pages }}.
                                    </a>
                                {% endif %}
                                </li> 
                                {% if enrolledStudentsPerSubject.has_next %}
                                <li class="waves-effect"><a href="?enrolledStudent_page={{ enrolledStudentsPerSubject.next_page_number }}&enrolledStudent_query={{ request.GET.enrolledStudent_query }}"><i class="material-icons">chevron_right</i></a></li>
                                <li class="waves-effect"><a href="?enrolledStudent_page={{ enrolledStudentsPerSubject.paginator.num_pages }}&enrolledStudent_query={{ request.GET.enrolledStudent_query }}"><i class="material-icons">last_page</i></a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
                
        
                    
                    <center><b><h6><hr class="grey"></h6></b></center>
                <a  href="{% url 'grading_system:view_assigned_subject' %}" class="col s12">Back</a>
        </div>
        <br><br>
    </div>
{% endblock content %}