account/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views
from . import views


app_name = "account"

urlpatterns = [
    path('account/', views.dashboard, name='dashboard'),
    path('account/view/edit/profile/',
         views.view_edit_profile, name='view_edit_profile'),
    path('accounts/change_password/',
         views.change_password, name='change_password'),
]

announcement/urls.py
from django.urls import path
from . import views


app_name = 'announcement'

urlpatterns = [
    path('dmca/view/announcement/',
         views.view_announcement, name='view_announcement'),
    path('dmca/view/announcement/detail/<int:a_id>/<slug:a_slug>/',
         views.view_announcement_detail, name='view_announcement_detail'),
    path('dmca/edit/announcement/<int:a_id>/<slug:a_slug>/',
         views.edit_announcement, name='edit_announcement'),
    path('dmca/create/announcement/',
         views.create_announcement, name='create_announcement'),
    path('dmca/view/edit/draft/announcement/',
         views.draft_published_announcement, name='draft_published_announcement'),
    path('dmca/delete/announcement/<int:a_id>/<slug:a_slug>/',
         views.delete_announcement, name='delete_announcement'),
    path('dmca/delete/comment/<int:a_id>/<slug:a_slug>/<int:comment_id>/',
         views.delete_comment, name='delete_comment'),
    path('dmca/edit/comment/<int:a_id>/<slug:a_slug>/<int:comment_id>/',
         views.edit_comment, name='edit_comment'),
    path('dmca/view/comment/profile/<int:target_user_id>/<target_user_short_name>/<int:a_id>/',
         views.view_user_profile_comment, name='view_user_profile_comment'),
    path('dmca/view/all-created/announcement/',
         views.created_announcement, name='created_announcement'),
]

grading_system/urls.py
from django.urls import path
from . import views

app_name = 'grading_system'

urlpatterns = [
    path('faculty/assigned/subjects/',
         views.view_assigned_subject, name="view_assigned_subject"),
    path('faculty/view/students/per/subject/<int:level_section_id>/<int:subject_id>/',
         views.view_students_per_subject, name="view_students_per_subject"),
    path('faculty/view/student/profile/<int:user_id>/<short_name>/',
         views.view_student_profile, name='view_student_profile'),
    path('faculty/edit/student/subject-grade/<int:user_id>/<user_full_name>/<int:subject_grade_id>/',
         views.edit_student_subjectgrade, name='edit_student_subjectGrade'),
    path('faculty/view/student/final-grade/',
         views.view_students_finalgrade, name='view_students_finalgrade'),
    path('faculty/edit/student/final-grade/<int:user_id>/<int:level_id>/',
         views.edit_student_finalgrade, name='edit_student_finalgrade'),
    path('student/subject/<student_level>/<student_section>/',
         views.student_level_section_subject, name="student_level_section_subject"),
    path('student/view/faculty/profile/<int:user_id>/<short_name>/',
         views.view_faculty_profile, name='view_faculty_profile'),
    path('student/view/all/grades/',
         views.view_all_grades, name='view_all_grades'),
]

projectDMCA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'DMCA Administration'
admin.site.index_title = 'DMCA Administration'
admin.site.site_title = 'Admin Site'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='account')),
    # login, logout and password_reset form
    path('account/', include('django.contrib.auth.urls')),
    path('administrator/', include('administrator.urls', namespace='administrator')),
    path('announcement/', include('announcement.urls', namespace='announcement')),
    path('academic/', include('grading_system.urls', namespace='grading_system')),
    path('accounting/transaction/', include('accounting_transaction.urls',
                                            namespace='accounting_transaction')),
    path('', include('admission.urls', namespace='admission')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

announcement/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.auth import get_user_model
from account.models import LevelAndSection
from django.utils.text import slugify
from datetime import datetime

# from gdstorage.storage import GoogleDriveStorage
# gd_storage = GoogleDriveStorage()
# Create your models here.
User = get_user_model()


class Announcement(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='created_announcements')
    tags = TaggableManager(blank=True)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish_date')
    body = models.TextField()
    # upload_to='dmca/files/', storage=gd_storage
    file = models.FileField(
        upload_to='file/announcement/%Y/%m/%d/', blank=True, null=True)
    publish_date = models.DateTimeField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='published')
    send_to_group = models.ForeignKey(
        LevelAndSection, on_delete=models.CASCADE,
        related_name='group_announcements', null=True,
        blank=True, verbose_name="Send to what Year and Section"
    )
    send_to_all = models.BooleanField(
        default=False, verbose_name="Send to all users?")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        if self.status == 'published' and self.publish_date is None:
            self.publish_date = datetime.now()
        super(Announcement, self).save(*args, **kwargs)

    @property
    def get_absolute_url(self):
        return reverse(
            "announcement:view_announcement_detail",
            args=[self.id, self.slug]
        )

    @property
    def get_absolute_url_for_edit(self):
        return reverse(
            "announcement:edit_announcement",
            args=[self.id, self.slug]
        )

    @property
    def get_absolute_url_for_delete(self):
        return reverse(
            "announcement:delete_announcement",
            args=[self.id, self.slug]
        )

    class Meta:
        ordering = ('-publish_date',)

    def __str__(self):
        return '{} by {}.'.format(self.title, self.author.get_full_name)


class Comment(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='personal_comment', null=True)
    announcement = models.ForeignKey(
        Announcement, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return 'Comment By {} on {}'.format(self.author.get_full_name, self.announcement)

announcement/views.py
from django.shortcuts import render, reverse, redirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from . import forms
from django.contrib import messages
from .models import Announcement, Comment
from account.models import LevelAndSection
from django.utils import timezone
from datetime import datetime
from django.core.paginator import (PageNotAnInteger, EmptyPage, Paginator)

# Create your views here.

User = get_user_model()


@login_required
def view_announcement(request):
    school_announcement_list = Announcement.objects.filter(
        send_to_all=True, status='published', publish_date__lte=datetime.now()).order_by('-publish_date')
    school_paginator = Paginator(school_announcement_list, 10)
    school_page = request.GET.get('school_page')
    try:
        school_announcement = school_paginator.page(school_page)
    except PageNotAnInteger:
        school_announcement = school_paginator.page(1)
    except EmptyPage:
        school_announcement = school_paginator.page(school_paginator.num_pages)
    context = {'request': request, 'school_announcement': school_announcement}
    group_announcement_list = []
    group_announcement = level_and_section = None
    if request.user.is_staff:
        group_announcement_list = Announcement.objects.filter(
            send_to_all=False, status='published', author=request.user,
            publish_date__lte=timezone.now()).order_by('-publish_date')
    if request.user.is_student and request.user.student_profile.level_and_section:
        group_announcement_list = Announcement.objects.filter(
            send_to_group=request.user.student_profile.level_and_section,
            status='published',
            publish_date__lte=timezone.now()).order_by('-publish_date')
    elif request.user.is_teacher:
        level_and_section = LevelAndSection.objects.filter(
            adviser=request.user.faculty_profile)
        group_announcement_list = Announcement.objects.filter(
            send_to_group__adviser__user=request.user,
            status='published',
            publish_date__lte=timezone.now()).order_by('-publish_date')
    group_paginator = Paginator(group_announcement_list, 10)
    group_page = request.GET.get('group_page')
    try:
        group_announcement = group_paginator.page(group_page)
    except PageNotAnInteger:
        group_announcement = group_paginator.page(1)
    except EmptyPage:
        group_announcement = group_paginator.page(
            group_paginator.num_pages)
    context.update({'group_announcement': group_announcement,
                    'level_and_section': level_and_section})
    return render(request, 'view_announcement.html', context)


@login_required
def view_announcement_detail(request, a_id, a_slug):
    announcement = Announcement.objects.get(id=a_id, slug=a_slug)
    comment_list = announcement.comments.filter(active=True)
    paginator = Paginator(comment_list, 5)
    page = request.GET.get('page')
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)
    if request.method == 'GET':
        comment_form = forms.CommentForm()
    elif request.method == 'POST':
        comment_form = forms.CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.author = request.user
            new_comment.announcement = announcement
            new_comment.save()
            return HttpResponseRedirect(reverse('announcement:view_announcement_detail', args=[a_id, a_slug]))
    context = {'announcement': announcement,
               'comment_form': comment_form, 'comments': comments, 'request': request, 'comment_list': comment_list}
    return render(request, 'announcement_detail.html', context)


@login_required
def create_announcement(request):
    if request.user.is_student:
        raise PermissionDenied
    if request.method == 'GET':
        create_announcement_form = forms.AnnouncementForm()
    elif request.method == 'POST':
        create_announcement_form = forms.AnnouncementForm(
            data=request.POST, files=request.FILES)
        if create_announcement_form.is_valid():
            new_announcement = create_announcement_form.save(commit=False)
            new_announcement.author = request.user
            new_announcement.save()
            create_announcement_form.save_m2m()
            return HttpResponseRedirect(reverse('announcement:view_announcement'))
    context = {'create_announcement_form': create_announcement_form,
               'request': request}
    return render(request, 'create_announcement.html', context)


@login_required
def edit_announcement(request, a_id, a_slug):
    announcement = Announcement.objects.get(id=a_id, slug=a_slug)
    if request.user.is_student or announcement.author != request.user:
        raise PermissionDenied
    if request.method == 'GET':
        announcement_edit_form = forms.AnnouncementForm(instance=announcement)
    elif request.method == 'POST':
        announcement_edit_form = forms.AnnouncementForm(
            data=request.POST, instance=announcement, files=request.FILES)
        if announcement_edit_form.is_valid():
            announcement_edit_form.save()
            messages.success(request, 'Your Announcement was updated.')
            return HttpResponseRedirect(announcement.get_absolute_url_for_edit)
    context = {'announcement_edit_form': announcement_edit_form,
               'announcement': announcement}
    return render(request, 'edit_announcement.html', context)


@login_required
def draft_published_announcement(request):
    if request.user.is_student:
        raise PermissionDenied
    draft_announcement_list = Announcement.objects.filter(
        status='draft', author=request.user).order_by('-publish_date')
    draft_announcement_paginator = Paginator(draft_announcement_list, 10)
    draft_page = request.GET.get('draft_page')
    try:
        draft_announcement = draft_announcement_paginator.page(draft_page)
    except PageNotAnInteger:
        draft_announcement = draft_announcement_paginator.page(1)
    except EmptyPage:
        draft_announcement = draft_announcement_paginator.page(
            draft_announcement_paginator.num_pages)
    published_announcement_list = Announcement.objects.filter(
        status='published', author=request.user).order_by('-publish_date')
    published_announcement_paginator = Paginator(
        published_announcement_list, 10)
    published_page = request.GET.get('published_page')
    try:
        published_announcement = published_announcement_paginator.page(
            published_page)
    except PageNotAnInteger:
        published_announcement = published_announcement_paginator.page(1)
    except EmptyPage:
        published_announcement = published_announcement_paginator.page(
            published_announcement_paginator.num_pages)
    context = {'draft_announcement': draft_announcement, 'request': request,
               'published_announcement': published_announcement}
    return render(request, 'draft_published_announcement.html', context)


def created_announcement(request):
    if request.user.is_student:
        raise PermissionDenied
    created_announcements = Announcement.objects.filter(author=request.user)
    context = {'created_announcements': created_announcements,
               'request': request}
    return render(request, 'created_announcement.html', context)


@login_required
def delete_announcement(request, a_id, a_slug):
    announcement = Announcement.objects.get(id=a_id, slug=a_slug)
    if request.user.is_student or request.user != announcement.author:
        raise PermissionDenied
    announcement.delete()
    return HttpResponseRedirect(reverse('announcement:view_announcement'))


@login_required
def delete_comment(request, a_id, a_slug, comment_id):
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return HttpResponseRedirect(reverse('announcement:view_announcement_detail', args=[a_id, a_slug]))


@login_required
def edit_comment(request, a_id, a_slug, comment_id):
    comment_instance = Comment.objects.get(
        id=comment_id, announcement__id=a_id, announcement__slug=a_slug)
    if request.method == 'GET':
        edit_comment_form = forms.EditCommentForm(instance=comment_instance)
    elif request.method == 'POST':
        edit_comment_form = forms.EditCommentForm(
            instance=comment_instance, data=request.POST)
        if edit_comment_form.is_valid():
            edit_comment_form.save()
            redirect_to = reverse(
                'announcement:view_announcement_detail', args=[a_id, a_slug])
            return redirect(redirect_to)
    context = {'edit_comment_form': edit_comment_form,
               'comment_instance': comment_instance}
    return render(request, 'edit_comment.html', context)


@login_required
def view_user_profile_comment(request, target_user_id, target_user_short_name, a_id):
    announcement = Announcement.objects.get(id=a_id)
    target_user = User.objects.get(id=target_user_id)
    context = {'request': request, 'target_user': target_user,
               'announcement': announcement}
    return render(request, 'view_user_profile_comment.html', context)

announcement/templates/announcements_with_similar_tags.html
{% load staticfiles %}
{% if similar_announcements %}
{% for announcement in similar_announcements %}
<a href="{% url 'announcement:view_announcement_detail' announcement.id announcement.slug %}">
    {{ announcement.title }}
</a> &nbsp;
{% endfor %}
{% endif %}

announcement/templates/create_announcement.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ request.user.get_short_name }} | Create Announcement{% endblock title %}
{% block content %}
<div class="white">
    <br>
    <div class="container">
        <form action="." method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="row">
                <div class="col s4">
                    <br><br>
                    {% if request.user.profile.photo.url is not None %}
                    <center><img class="circle" src="{{ request.user.profile.photo.url }}" style="height: 200px; width:200px; object-fit: cover; " /></center>
                    {% elif request.user.gender == "female" %}
                    <center><img class="circle" src="{% static "img/girl.png" %}" style="height: 200px; width:200px; object-fit: cover; " /></center>
                    {% elif request.user.gender == "male" %}
                    <center><img class="circle" src="{% static "img/boy.png" %}" style="height: 200px; width:200px; object-fit: cover; " /></center>
                    {% endif %}

                    <h6 class="center"><u><b>{{ request.user.get_full_name }}</b></u></h6>
                    <center><h6>Author</h6></center>
                </div>
                <div class="col s8">
                    <div class="card">
                        <div class="card-content row">
                            <div class="col s12">
                                <div class="input-field">
                                    <i class="material-icons prefix">title</i>
                                    <input type="text" name="title" maxlength="250" class="validate" required id="id_title">
                                    <label for="id_title">Announcement Title</label>
                                </div>
                            </div>
                            <div class="col s12">
                                <div class="input-field">
                                    <i class="material-icons prefix">title</i>
                                    <input type="text" name="tags" required id="id_tags" maxlength="250" class="validate">
                                    <label for="id_tags">Tags</label> 
                                    <span class="helptext">A comma-separated list of tags.</span>
                                </div>
                            </div>
                            <div class="col s12">
                                <div class="input-field">
                                    <i class="material-icons prefix">message</i>
                                    <textarea class="materialize-textarea" name="body" cols="80" rows="20" required id="id_body"></textarea>
                                    <label for="id_body">Type your Message Here....</label>
                                </div>
                            </div>
                            <div class="col s12">
                                <div class="right">
                                    <label>
                                        <input type="checkbox" name="send_to_all" id="id_send_to_all">
                                        <span>Send to All?</span>
                                    </label>
                                </div>
                            </div>
                            <div class="col s12">
                                <div class="file-field input-field">
                                    <div class="btn">
                                        <span><i class="material-icons right">attachment</i>Attach File(s)</span>
                                        <input type="file" name="file" id="id_file">
                                    </div>
                                    <div class="file-path-wrapper">
                                        <input class="file-path validate" type="text">
                                    </div>
                                </div>
                            </div>
                            <div class="col s8">
                                <label for="id_send_to_group">Send to what Year and Section:</label> 
                                <select name="send_to_group" id="id_send_to_group">
                                {% for value in create_announcement_form.send_to_group %}
                                    {{ value }}
                                {% endfor %}
                                </select>
                            
                            </div>
                            <div class="col s6">
                                <label for="id_status">Status</label>
                                <select name="status" id="id_status">
                                    <option value="draft">Draft</option>
                                    <option value="published" selected >Published</option>
                                </select>
                            </div>
                            <div class="col s3">
                                <button class="btn btn-large red waves-effect" type="reset">Reset <i class="material-icons right">format_clear</i></button>
                            </div>
                            <div class="col s3">
                                <div class="center-align">
                                    <button class="btn btn-large indigo waves-effect" type="submit">Send<i class="material-icons right">send</i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <br><br>
</div>
{% endblock content %}

announcement/templates/edit_announcement.html
{% extends 'base.html' %}
{% block title %}{{ request.user.get_full_name }} | Messages{% endblock title %}
{% block content%}
{% load staticfiles %}
<div class="white">
    <br><br>
    <div class="row">
        <div class="col s4">
            <br><br>
            {% if request.user.profile.photo.url is not None %}
            <center><img class="circle" src="{{ request.user.profile.photo.url }}" style="height: 200px; width:200px; object-fit: cover; " /></center>
            {% elif request.user.gender == "female" %}
            <center><img class="circle" src="{% static " img/girl.png" %}" style="height: 200px; width:200px; object-fit: cover; " /></center>
            {% elif request.user.gender == "male" %}
            <center><img class="circle" src="{% static " img/boy.png" %}" style="height: 200px; width:200px; object-fit: cover; " /></center>
            {% endif %}

            <h6 class="center"><u><b>{{ request.user.get_full_name }}</b></u></h6>
            <center>
                <h6>Author</h6>
            </center>
        </div>
        <div class="col s8">
            <div class="card">
                <div class="card-content">
                    {% if messages %}
                    {% for message in messages %}
                    <h4>{{ message }}</h4>
                    {% endfor %}
                    {% endif %}

                    <form method="POST" action="{% url 'announcement:edit_announcement' announcement.id announcement.slug %}"
                        enctype="multipart/form-data">
                        {% csrf_token %}
                        <p><label for="id_title">Title:</label> <input type="text" name="title" value="{{ announcement_edit_form.title.value }}"
                                maxlength="250" required id="id_title"></p>
                        <p><label for="id_tags">Tags:</label> <input type="text" name="tags" value="{%  for tag in announcement_edit_form.tags.value  %}{{ tag.tag }},{% endfor %}"
                                id="id_tags"> <span class="helptext">A comma-separated list of tags.</span></p>
                        <p><label for="id_body">Content:</label> <textarea name="body" cols="40" rows="10" required id="id_body">{{ announcement_edit_form.body.value }}</textarea></p>
                        <p>
                            <label for="id_file">Attach File/s:</label>
                            {% if announcement_edit_form.file.value %}
                            Currently:
                            <a href="{{ announcement_edit_form.file.value.url }}">
                                {{ announcement_edit_form.file.value }}</a>
                            <label for="file-clear_id">
                                <input type="checkbox" name="file-clear" id="file-clear_id">
                                <span>Clear</span>
                            </label><br>
                            Change: <input type="file" name="file" id="id_file">
                            {% elif announcement_edit_form.file.url is None %}
                            <input type="file" name="file" id="id_file" >
                            {% endif %}
                        </p>
                        </p>
                        <p><label for="id_send_to_group">Send to what Year and Section:</label> <select name="send_to_group"
                                id="id_send_to_group">
                                {% for option in announcement_edit_form.send_to_group %}
                                {{ option }}
                                {% endfor %}
                            </select></p>
                        <p><label for="id_send_to_all">
                                {% if announcement_edit_form.send_to_all.value %}
                                <input type="checkbox" name="send_to_all" id="id_send_to_all" checked>
                                {% else %}
                                <input type="checkbox" name="send_to_all" id="id_send_to_all">
                                {% endif %}
                                <span>Send to all?</span></label>

                        </p>
                        <input type="submit" value="Submit" />
                    </form>
                    <a href="{{ announcement.get_absolute_url }}">Back</a>
                </div>
            </div>
        </div>
    </div>
    <br><br>
</div>
{% endblock content %}

announcement/templates/edit_comment.html
{% extends 'base.html' %}
{% block title %}Edit Comment{% endblock title %}
{% block content%}
{% load staticfiles %}
<div class="white">
<br><br>

<div class="container">
    <div class="row">
        <div class="col s4">
            <br><br>
            {% if request.user.profile.photo.url is not None %}
            <center><img class="circle" src="{{ request.user.profile.photo.url }}" style="height: 200px; width:200px; object-fit: cover; " /></center>
            {% elif request.user.gender == "female" %}
            <center><img class="circle" src="{% static "img/girl.png" %}" style="height: 200px; width:200px; object-fit: cover; " /></center>
            {% elif request.user.gender == "male" %}
            <center><img class="circle" src="{% static "img/boy.png" %}" style="height: 200px; width:200px; object-fit: cover; " /></center>
            {% endif %}

            <h6 class="center"><u><b>{{ request.user.get_full_name }}</b></u></h6>
            <center><h6>Author</h6></center>
        </div>
        <div class="col s8">
            <div class="card">
                <div class="card-content">
                    <h6 class="center"><b>Edit your Comment for {{ comment_instance.announcement.title }}</b></h6>
                    <form method="POST" 
                    action="{% url 'announcement:edit_comment' comment_instance.announcement.id comment_instance.announcement.slug comment_instance.id %}">
                        {% csrf_token %}
                        {{ edit_comment_form }}
                        <input class="btn waves-effect" type="submit" value="Submit" title="Edit Comment"/>
                        <a class="btn red waves-effect" href="{% url 'announcement:view_announcement_detail' comment_instance.announcement.id comment_instance.announcement.slug %}">
                        Cancel
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

    
</div>
<br><br>
</div>
{% endblock content %}

announcement/templates/latest_school_announcement.html
{% load staticfiles %}
<div>
    <ul class="collection">
        {% for announcement in latest_school_announcements %}
        <li class="collection-item avatar">
            {% if announcement.author.profile.photo.url is not None %}
                <img class="circle" src="{{ announcement.author.profile.photo.url }}" alt="{{ announcement.author.get_full_name }}" style="object-fit: cover; ">
            {% elif announcement.author.gender == "female" %}
                <img src="{% static 'img/girl.png' %}" alt="{{ announcement.author.get_full_name }}" style="max-width:100%; object-fit:cover">
            {% elif announcement.author.gender == "male" %}
                <img src="{% static 'img/boy.png' %}" alt="{{ announcement.author.get_full_name }}" style="max-width:100%; object-fit:cover">
            {% endif %}
            <span class="title"><a href="{% url 'announcement:view_announcement_detail' announcement.id announcement.slug %}">
                    {{announcement.title }}</a></span>
            <p><small> Date Posted: {{ announcement.publish_date }}</small></p>
        </li>
        {% endfor %}
    </ul>
</div>