account/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views
from . import views


app_name = "account"

urlpatterns = [
    path('account/', views.dashboard, name='dashboard'),
    path('account/view/edit/profile/',
         views.view_edit_profile, name='view_edit_profile'),
    path('accounts/change_password/',
         views.change_password, name='change_password'),
]

accounting_transaction/urls.py
from django.urls import path
from . import views
# Create your url patterns here

app_name = "accounting_transaction"

urlpatterns = [
    path('view/list/', views.view_user_list, name='view_user_list'),
    path('view/statement/<user_full_name>/<int:user_id>/',
         views.view_statement, name='view_statement'),
    path('delete/statement/<int:statement_id>/<student_full_name>/<int:student_id>/',
         views.delete_statement, name='delete_statement'),
    path('update/statement/<int:statement_id>/<student_full_name>/<int:student_id>/',
         views.update_statement, name='update_statement'),
    path('view/account-statement/',
         views.student_view_statement, name='student_view_statement'),
]

administrator/urls.py
from django.urls import path
from . import views
# Create your forms here


app_name = 'administrator'

urlpatterns = [
    path('dmca/create/user/', views.create_user, name='create_user'),
    path('dmca/create/user/done/', views.create_user_done, name='create_user_done'),
    path('dmca/view/users/', views.view_users, name='view_users'),
    path('dmca/delete/user/<int:user_id>/',
         views.delete_user, name='delete_user'),
    path('dmca/edit/user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('dmca/edit/level/section/<int:level_section_id>',
         views.edit_level_section, name='edit_level_section'),
    path('dmca/view/level/section/',
         views.view_level_section, name='view_level_section'),
    path('dmca/delete/level/section/<int:level_section_id>',
         views.delete_level_section, name='delete_level_section'),
    path('dmca/create/subject/<int:user_id>/',
         views.create_subject, name='create_subject'),
    path('dmca/edit/subject/<slug:subject_slug>/<int:user_id>/',
         views.edit_subject, name='edit_subject'),
    path('dmca/delete/subject/<slug:subject_slug>/<int:user_id>/',
         views.delete_subject, name='delete_subject'),
    path('dmca/enroll/subject/<int:user_id>/<user_full_name>/',
         views.enrollment_admission_student, name='enrollment_admission'),
    path('dmca/delete/subject/grade/<int:user_id>/<user_full_name>/<int:subject_grade_id>/',
         views.delete_subject_grade, name='delete_subject_grade'),
    path('dmca/edit/subject/grade/<int:user_id>/<user_full_name>/<int:subject_grade_id>/',
         views.edit_subjectGrade_admin, name='edit_subjectGrade_admin'),
    path('dmca/create/final/grade/',
         views.create_student_finalLevelGradeAdmin, name='create_student_finalLevelGradeAdmin'),
    path('dmca/edit/final/grade/<int:final_grade_id>/<user_full_name>/',
         views.edit_student_finalLevelGradeAdmin, name='edit_student_finalLevelGradeAdmin'),
    path('dmca/delete/grade/<int:final_grade_id>/<user_full_name>/',
         views.delete_student_finalLevelGradeAdmin, name='delete_student_finalLevelGradeAdmin'),
    path('dmca/update/statement/<int:statement_id>/<student_full_name>/<int:student_id>/',
         views.update_statement_admin, name='update_statement_admin'),
    path('dmca/view/statement/<user_full_name>/<int:user_id>/',
         views.view_statement_admin, name='view_statement_admin'),
    path('dmca/delete/statement/<int:statement_id>/<student_full_name>/<int:student_id>/',
         views.delete_statement_admin, name='delete_statement_admin'),
    path('dmca/view/create/year-level/',
         views.view_create_year_level, name='view_create_year_level'),
    path('dmca/view/appointment-requests/',
         views.view_appointment_request, name='view_appointment_request'),
    path('dmca/delete/view/appointment-request/<int:appointment_request_id>/',
         views.delete_appointment_request, name='delete_appointment_request'),
    path('dmca/update/appointment-request/<int:appointment_request_id>/<slug:appointment_request_slug>/',
         views.update_appointment_request, name='update_appointment_request'),
]

projectDMCA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'DMCA Administration'
admin.site.index_title = 'DMCA Administration'
admin.site.site_title = 'Admin Site'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='account')),
    # login, logout and password_reset form
    path('account/', include('django.contrib.auth.urls')),
    path('administrator/', include('administrator.urls', namespace='administrator')),
    path('announcement/', include('announcement.urls', namespace='announcement')),
    path('academic/', include('grading_system.urls', namespace='grading_system')),
    path('accounting/transaction/', include('accounting_transaction.urls',
                                            namespace='accounting_transaction')),
    path('', include('admission.urls', namespace='admission')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounting_transaction/models.py
from django.db import models
from account.models import StudentProfile
from grading_system.models import SY
from datetime import datetime


# Create your models here.
class Statement(models.Model):
    current_school_year = str(datetime.now().year) + \
                          "-" + str(datetime.now().year + 1)
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    school_year = models.CharField(
        max_length=25, choices=SY, default=str(current_school_year))
    break_down = models.TextField(null=True, blank=True)
    assessment = models.DecimalField(
        default=0.0, max_digits=12,
        decimal_places=2, verbose_name="Assessment (Php)")
    payment = models.DecimalField(
        default=0.0, max_digits=12,
        decimal_places=2, verbose_name="Payment (Php)")
    balance = models.DecimalField(
        default=0.0, max_digits=12,
        decimal_places=2, verbose_name="Balance (Php)")
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.student.user.get_full_name + " " + self.school_year

    def save(self, *args, **kwargs):
        if self.assessment - self.payment != self.balance:
            self.balance = self.assessment - self.payment
        super(Statement, self).save(*args, **kwargs)

accounting_transaction/forms.py
from django import forms
from .models import Statement
# Create your forms here


# for admin account only
class StatementCreateForm(forms.ModelForm):
    class Meta:
        model = Statement
        exclude = ['date_created', 'updated']


# for staff account only
class StatementAddForm(forms.ModelForm):
    class Meta:
        model = Statement
        exclude = ['date_created', 'updated', 'student']

accounting_transaction/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from .models import Statement
from django.core.exceptions import PermissionDenied
from django.contrib.auth import get_user_model
from .forms import StatementAddForm
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required

# Create your views here.

User = get_user_model()


# staff account only
@login_required
def view_user_list(request):
    context = {'request': request}
    if not request.user.is_staff:
        raise PermissionDenied
    student_list = User.objects.filter(
        is_student=True).order_by('-date_created')
    student_query = request.GET.get("student_query")
    if student_query:
        student_list = student_list.filter(
            Q(first_name__icontains=student_query) |
            Q(last_name__icontains=student_query) |
            Q(middle_name__icontains=student_query) |
            Q(email__icontains=student_query) |
            Q(student_profile__level_and_section__level__level__icontains=student_query) |
            Q(student_profile__learner_reference_number__icontains=student_query)).distinct()
    # Student Pagination
    student_paginator = Paginator(student_list, 20)
    student_page = request.GET.get('student_page')
    try:
        students = student_paginator.page(student_page)
    except PageNotAnInteger:
        students = student_paginator.page(1)
    except EmptyPage:
        students = student_paginator.page(student_paginator.num_pages)
    context['students'] = students
    return render(request, 'view_user_list.html', context)


# staff account only
@login_required
def update_statement(request, statement_id, student_full_name, student_id):
    if not request.user.is_staff:
        raise PermissionDenied
    student_user = User.objects.get(id=student_id)
    statement_instance = Statement.objects.get(id=statement_id)
    context = {
        'request': request, 'student_user': student_user,
        'statement_instance': statement_instance,
    }
    if request.method == 'GET':
        update_statement_form = StatementAddForm(instance=statement_instance)
    elif request.method == 'POST':
        update_statement_form = StatementAddForm(
            data=request.POST, instance=statement_instance)
        if update_statement_form.is_valid():
            update_statement_form.save()
            messages.success(request, 'Statement Updated Sucessfully')
            return HttpResponseRedirect(
                reverse(
                    'accounting_transaction:update_statement',
                    args=[statement_id, student_full_name, student_id]
                )
            )
    context['update_statement_form'] = update_statement_form
    return render(request, 'update_statement.html', context)


# staff account only
@login_required
def view_statement(request, user_full_name, user_id):
    if not request.user.is_staff:
        raise PermissionDenied
    student_user = User.objects.get(id=user_id)
    account_statements = Statement.objects.filter(
        student=student_user.student_profile).order_by('school_year')
    context = {
        'request': request, 'student_user': student_user,
        'account_statements': account_statements,
    }
    if request.method == 'GET':
        add_statement_form = StatementAddForm()
    elif request.method == 'POST':
        add_statement_form = StatementAddForm(data=request.POST)
        if add_statement_form.is_valid():
            new_statement = add_statement_form.save(commit=False)
            new_statement.student = student_user.student_profile
            new_statement.save()
            message = 'New Account Statement Added for {}'.format(
                student_user.get_full_name)
            messages.success(request, message)
            return HttpResponseRedirect(
                reverse(
                    'accounting_transaction:view_statement',
                    args=[student_user.get_full_name, student_user.id]
                )
            )
    context['add_statement_form'] = add_statement_form
    return render(request, 'view_statement.html', context)


def delete_statement(request, statement_id, student_full_name, student_id):
    if not request.user.is_staff:
        raise PermissionDenied
    statement_instance = Statement.objects.get(id=statement_id)
    statement_instance.delete()
    return HttpResponseRedirect(
        reverse(
            'accounting_transaction:view_statement',
            args=[student_full_name, student_id]
        )
    )


# for student account only
@login_required
def student_view_statement(request):
    if not request.user.is_student:
        raise PermissionDenied
    student_statements = Statement.objects.filter(student__user=request.user)
    statement_paginator = Paginator(student_statements, 10)
    statement_page = request.GET.get('statement_page')
    try:
        statements = statement_paginator.page(statement_page)
    except PageNotAnInteger:
        statements = statement_paginator.page(1)
    except EmptyPage:
        statements = statement_paginator.page(statement_paginator.num_pages)
    context = {'request': request, 'statements': statements}
    return render(request, 'student_view_statement.html', context)

accounting_transaction/templates/add_statement.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Add Statement</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    
</body>
</html>

accounting_transaction/templates/student_view_statement.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}View Statement{% endblock title %}
{% block content %}
<div class="white">
<br><br>

    <div>
        <ul>
            {% if statements %}
            {% for statement in statements %}
            <li>SY: {{ statement.school_year }}</li>
            <li>Break Down/Details: {{ statement.break_down }}</li>
            <li>Assessment: {{ statement.assessment }}</li>
            <li>Payment: {{ statement.payment }}</li>
            <li>Remaining Balance: {{ statement.balance }}</li>
            <li>Updated: {{ statement.updated }}</li>
            <br />
            {% endfor %}
            {% else %}
            <center><img src="{% static 'img/money.svg' %}" style="object-fit: fill; height: 250px"> <br><h5><b> No Transaction Record for this Account Yet.</b></h5></center>
            {% endif %}
        </ul>
        <div class="pagination right col s12">
            <span class="step-links">
                {% if statements.has_previous %}
                <a href="?statement_page=1">&laquo; first</a>
                <a href="?statement_page={{ statements.previous_page_number }}">previous</a>
                {% endif %}

                {% if statements %}
                <span class="current">
                    Page {{ statements.number }} of {{ statements.paginator.num_pages }}.
                </span>
                {% endif %}

                {% if statements.has_next %}
                <a href="?statement_page={{ statements.next_page_number }}">next</a>
                <a href="?statement_page={{ statements.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>

    </div>
<br><br>
</div>
{% endblock content %}

accounting_transaction/templates/update_statement.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Update Statement</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>

<body>
    <div>
        <p>Name: {{ statement_instance.student.user.get_full_name }}</p>
        <p>SY: {{ statement_instance.school_year }}</p>
        <p>Year and Section: {{ statement_instance.student.level_and_section }}</p>
    </div>
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
        {% if request.user.is_superuser and request.user.is_staff %}
        <form method="POST" action="{% url 'administrator:update_statement_admin' statement_instance.id student_user.get_full_name student_user.id %}">
            {% csrf_token %}
            {{ update_statement_form.as_p }}
            <input type="submit" value="Submit" />
        </form>
    </ul>

    <a href="{% url 'administrator:view_statement_admin' student_user.get_full_name student_user.id %}"><button>Back</button></a>
    <a href="{% url 'administrator:view_users' %}"><button>View Users</button></a>
    {% elif request.user.is_staff %}
    <form method="POST" action="{% url 'accounting_transaction:update_statement' statement_instance.id student_user.get_full_name student_user.id %}">
        {% csrf_token %}
        {{ update_statement_form.as_p }}
        <input type="submit" value="Submit" />
    </form>
    </ul>

    <a href="{% url 'accounting_transaction:view_statement' student_user.get_full_name student_user.id %}"><button>Back</button></a>
    <a href="{% url 'accounting_transaction:view_user_list' %}"><button>Account Statements</button></a>
    {% endif %}
    <div>

    </div>
</body>

</html>

accounting_transaction/templates/view_statement.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}View Statement|{{ student_user.get_full_name }}{% endblock title %}
{% block content %}
<div class="white">
    <br><br>
    <div class="container">
            <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% if account_statements %}
                <table border="1">
                    <th>School Year</th>
                    <th>Assessment</th>
                    <th>Balance</th>
                    <th>Date</th>
                    <th>Updated</th>
                    <th>Option</th>
                    {% for statement in account_statements %}
                    <tr>
                        <td>{{ statement.school_year }}</td>
                        <td>{{ statement.assessment }}</td>
                        <td>{{ statement.balance }}</td>
                        <td>{{ statement.date_created }}</td>
                        <td>{{ statement.updated }}</td>
                        {% if request.user.is_superuser %}
                        <td>
                            <a href="{% url 'administrator:update_statement_admin' statement.id student_user.get_full_name student_user.id %}">Update</a>
                            <a href="{% url 'administrator:delete_statement_admin' statement.id student_user.get_full_name student_user.id %}"
                            onclick="return confirm('Are you sure you want to DELETE this Statement for {{ student_user.get_full_name }} ?')">Delete</a></td>
                        {% elif request.user.is_staff %}
                        <td><a href="{% url 'accounting_transaction:update_statement' statement.id student_user.get_full_name student_user.id %}">Update</a>
                            <a href="{% url 'accounting_transaction:delete_statement' statement.id student_user.get_full_name student_user.id %}"
                                onclick="return confirm('Are you sure you want to DELETE this Statement for {{ student_user.get_full_name }} ?')">Delete</a>
                        </td>
                        {% endif %}
            
                    </tr>
                    {% endfor %}
                </table>
                {% else %}
                <center><img src="{% static "img/project.svg" %}" style="object-fit: fill; height: 300px"> <br> <h5><b>No existing Record for this Account.</b></h5> </center>
                {% endif %}
            
                <div>
                    <h6>Add Statement for {{ student_user.get_full_name }}</h6>
                    {% if request.user.is_superuser %}
                    <form method="POST" action="{% url 'administrator:view_statement_admin' student_user.get_full_name student_user.id %}">
                        {% csrf_token %}
                        {{ add_statement_form.as_p }}
                        <input type="submit" value="Submit" />
                    </form>
                    <a href="{% url 'administrator:view_users' %}"><button>Back</button></a>
                    {% elif request.user.is_staff %}
                    <form method="POST" action="{% url 'accounting_transaction:view_statement' student_user.get_full_name student_user.id %}">
                        {% csrf_token %}
                        {{ add_statement_form.as_p }}
                        <input type="submit" value="Submit" />
                    </form>
                    <a href="{% url 'accounting_transaction:view_user_list' %}"><button>Back</button></a>
                    {% endif %}
            
                </div>
                <br>
    </div>
    

<br><br>br
</div>

{% endblock content %}

accounting_transaction/templates/view_user_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Balance Statement{% endblock title %}
{% block content %}
<div class="white">
    <br><br>
    <div>
        <form action="" method="GET">
                <input type="text" placeholder="Search Students" name="student_query" value="{{ request.GET.student_query }}" />
                <input type="submit" value="Search" />
            </form>
            <table border="1">
                <th>Full Name</th>
                <th>LRN</th>
                <th>Email</th>
                <th>Account Status</th>
                <th>Birthday</th>
                <th>Address</th>
                <th>Contact Number</th>
                <th>Parent/Guardian</th>
                <th>Contact Number</th>
                <th>Year and Section</th>
                <th>Options</th>
                {% for student in students %}
                <tr>
                    <td>{{ student.get_full_name }}</td>
                    <td>{{ student.student_profile.learner_reference_number }}</td>
                    <td>{{ student.email }}</td>
                    {% if student.is_active %}
                    <td>Active</td>
                    {% else %}
                    <td>Disabled</td>
                    {% endif %}
                    <td>{{ student.date_of_birth }}</td>
                    <td>{{ student.address }}</td>
                    <td>{{ student.profile.phone_number }}</td>
                    <td>{{ student.student_profile.guardian }}</td>
                    <td>{{ student.student_profile.guardian_contact_number }}</td>
                    <td>{{ student.student_profile.level_and_section }}</td>
                    <td>
                        <a href="{% url 'accounting_transaction:view_statement' student.get_full_name student.id %}" >Account Statements</a>
                        </a>
                    </td>
                </tr>
                {% empty %}
                Empty Result.
                {% endfor %}
            </table>
        </div>
                
        <div class="pagination">
            <span class="step-links">
                {% if students.has_previous %}
                <a href="?student_page=1&student_query={{ request.GET.student_query }}">&laquo; first</a>
                <a href="?student_page={{ student.previous_page_number }}&student_query={{ request.GET.student_query }}">previous</a>
                {% endif %}
        
                {% if students %}
                <span class="current">
                    Page {{ students.number }} of {{ students.paginator.num_pages }}.
                </span>
                {% endif %}
        
                {% if students.has_next %}
                <a href="?student_page={{ students.next_page_number }}&student_query={{ request.GET.student_query }}">next</a>
                <a href="?student_page={{ students.paginator.num_pages }}&student_query={{ request.GET.student_query }}">last
                    &raquo;</a>
                {% endif %}
            </span>
        </div> 
    </div>
    <br><br>
</div>

{% endblock content %}